### ISSUE TITLE
Set of primitive generators

### ISSUE THREAD

**Issue by Shimuuar** [lehins/random#5]
Any generic API will need to define set of primitive generators which  are used to define more complicated ones. Question of what this set should include are largely independent from other details of API and as such could discussed separately. In examples I assume some variant of monadic API 

### Proposal from #1 

```haskell
   genWord8  :: m Word8
   genWord16 :: m Word16
   genWord32 :: m Word32
   genWord64 :: m Word64
   genFloat  ::  m Float
   genDouble :: m Double
```

Basically this includes generators for all fixed width ints and for IEEE754 floats. 

### Whether floating point should be included

@Shimuuar: no
> Offhand I can say that I think Float & Double shouldn't be part of interface. They are trivially derived from uniform Word32/Word64. And there's problem: are we generating in [0,1] range? (0,1]?

@cartazio ???
> There’s several gotchas with those algorithms for float and double.
> 
> The usual unit interval used in extent Haskell Libs is wrong.
> 
> See the commented out bit linked herein
> https://github.com/haskell/random/blob/master/src/Data/Distribution/FloatingInterval.hs
>
> https://github.com/haskell/random/blob/master/src/Data/Distribution/FloatingInterval.hs

@lehins leans to no
> With regards to floating point numbers I am leaning towards not including them for consistency with ranges. Having a single efficient implementation for all RNGs that use either 32bits or 64bits seems like a better idea

So far it looks like general consensus is to make generators for floating point numbers derived.

### Inclusion of ranges
Another proposal by @shimuuar, `genWord32R n` generates values in range [0,n] inclusive.
```haskell
   genWord32  :: m Word32
   genWord32R :: Word32 -> m Word32
   genWord64  :: m Word64
   genWord64R:: Word64 -> m Word64
```
Arguments for inclusion `genWord32/64R`:

- Some PRNG (e.g. LCG) generate randoms in range other that full Word32/Word64. Implementing `genWord32/64R` in terms of 
- Even if PRNG produces uniform Word32/64 optimal implementation of `genWord32R` depend on whether generator produces Word32 or Word64
- @lehins argument in support of  nextWord8/16 could interpreted as support of `*R` variants: "We should allow a specific RNG to decide what is the most efficient way to generate 8 and 16 bits of random data". If PRNG should be able to decide what is best way to generate Word8, e.g. range [0,255] it should be able to decide how to generate other ranges

Argument for excluding `genWord8/16`:
> They're subsumed by `genWord32R`: `genWord8 = getWord32R 255`
Argument for inclusing `genWord8/16`:
> We should allow a specific RNG to decide what is the most efficient way to generate 8 and 16 bits of random data

**Comment by curiousleo** [comment]
I am also of the opinion that floats should _not_ be part of the primitive generator API.

The mental model I've come to is that of a "randomness source backend" (what we've so far called the "primitive generator API") and "random distribution frontend" API split.

### "Randomness source backend API"

*The "randomness source backend API" should be minimal: this is where we can plug in various PRNG algorithms.*

Its API should be close to the "native" output of the PRNG, i.e. there should be as little massaging of outputs as possible.

Ignoring LCGs, I believe that the natural API here would consist of `Word32` and `Word64` generators. That is what e.g. `splitmix`, `mwc-random` and `tf-random` support natively.

LCGs and other random number generators that do not natively generate `2^n` (for some `n`) bits natively, it gets a little more complicated - but I think we can come up with a "randomness source backend API" that covers those if we want.

### "Random distribution frontend API"

My inspiration here comes from [`System.Random.MWC.Distributions`](https://hackage.haskell.org/package/mwc-random-0.14.0.0/docs/System-Random-MWC-Distributions.html), which lives in `mwc-random` but is not actually specific to the MWC256 PRNG at all.

The point here is that so far we've been talking about e.g. drawing `Int`s and `Double`s uniformly from `[a, b)`, `[a, b]` and so forth. However, the Uniform distribution is just one amongst many - I expect the Normal distribution to be quite popular too.

Hence this proposal to think about the "randomness source backend" and the "random distribution frontend" separately.

*The "random distribution frontend" needs to be implemented only once. It exposes an API to draw a random value from a number of random distributions. It can use any PRNG that implements the "randomness source backend API" as its source of randomness.*

### Floats

Coming back to the original question: when we think of the "primitive generator API" as the "randomness source API", it is clear that floats should not be part of it, simply because there aren't any (well-known) PRNGs that natively output floats.

As a result, the ability to draw random floating point numbers (from a variety of distributions) is something that should be exposed by the "random distribution frontend API".

**Comment by cartazio** [comment]
Well said.

My inclination for portability is to have the defauktninterfsce for
randomness be in units of word64


For building up distributions a Monadic api allows for a very nice
combinators for wiring together various algorithms.

**Comment by Shimuuar** [comment]
@curiousleo I completely agree that we need only small set of primitives and just derive everything else from them. Problems is optimal implementation of some distributions is different for different generators. Even if we ignore LGCs. Take for example generation of Word32 in range `[0,2/3*maxBound]` 

 * If we implement it in terms of `nextWord32` it will require 1.5 generator iterations for both Word32 & Word64 based generators

 * If we implement it in terms of `nextWord64` it will require ~1 generator iteration for Word64 based generator, and ~2 for Word32 based one. 

So it make sense to include these functions (possibly with default implementation) into interface. There's ample precedent for doing so: `>>`, `<$`, `mconcat`, most of `Foldable`. As a bonus they nicely solve problem with LCG&Co 

Semantics is quite clear as well: it's possible to generate uniform distributions of any size as long as they fit into Word64. And I don't think there're other generator which may need specialization

> My inclination for portability is to have the defauktninterfsce for
randomness be in units of word64

To this I can only reply: "Nuts!" This will mean that say mwc-random will require two generator steps where one would suffice

**Comment by curiousleo** [comment]
> I completely agree that we need only small set of primitives and just derive everything else from them.

:+1: 

> Take for example generation of Word32 in range `[0,2/3*maxBound]`
> 
>     * If we implement it in terms of `nextWord32` it will require 1.5 generator iterations for both Word32 & Word64 based generators

To make sure we're on the same page: are you thinking of a specific algorithm for generating a `Word32` in the range `[0, 2/3*maxBound]` given a stream of random `Word32` (or `Word64`) values here? Which one?

**Comment by Shimuuar** [comment]
AFAIK there's only one such algorithm: sampling with rejection. Difference
are in how to compute result and test whether we need to retry most
efficiently. Especially to avoid expensive divisions

**Comment by cartazio** [comment]
Rejection sampling is a very nice and important primitive :)

**Comment by curiousleo** [comment]
> AFAIK there's only one such algorithm: sampling with rejection. Difference are in how to compute result and test whether we need to retry most efficiently. Especially to avoid expensive divisions

Thanks! I've found https://www.pcg-random.org/posts/bounded-rands.html to be a good reference.

**Comment by idontgetoutmuch** [comment]
@Shimuuar to be explicit, are you proposing this https://github.com/idontgetoutmuch/random/pull/1#issuecomment-586615921:

```
class Monad m => MonadRandom m where
  -- | Generate uniformly distributed 32-bit word
  uniformWord32    :: m Word32
  -- | Generate uniformly distributed 64-bit word
  uniformWord64    :: m Word64
  -- | Generate uniformly distributed 32-bit word in range [0,n]
  uniformRWord32   :: Word32 -> m Word32
  -- | Generate uniformly distributed 32-bit word in range [0,n]
  uniformRWord64   :: Word64 -> m Word64
```

If so: what about `split` and `next` and `genRange`. To be more concrete, what would e.g. `QuickCheck` and `random-fu` have to do to use the above interface (if that is what you are proposing - apologies if I am being presumptuous)? What about the many uses of such functions elsewhere?

**Comment by idontgetoutmuch** [comment]
I now agree that `Float` and `Double` should not be part of the primitive generator API. There are packages that provided distributions and a uniform distribution can be obtained from one of them if needed.

**Comment by Shimuuar** [comment]
@idontgetoutmuch Yes, that's right. I think there's still disagreement between @lehins and me on whether generators for Word8/16 should be included. I think there's no point since internally PRNG will work with at least 32bit numbers and they're completely subsumed by uniformRWord32/uniformWord32. @lehins thinks they should be included.

While generators for floating point shouldn't be part of low level API they absolutely must be part of package. I would expect that library user wouldn't use these low level functions much and instead would use some higher level API. Probably something along the lines of Random/Variate type class.

**Comment by lehins** [comment]
First of all, I think `MonadRandom` would be a bad design decision. There is already one available in [monad-source](https://hackage.haskell.org/package/random-source-0.3.0.6/docs/Data-Random-Source.html) and it is suffers from many problems (performance, every transformer will require an instance, etc.) Plus overall it becomes more complicated in using and complicates transition for the current stateful interface . Most importantly, if any one wants to use such interface they can just depend on `monad-source` already.

```haskell
class Monad m => MonadRandom m where
  -- | Generate uniformly distributed 32-bit word
  uniformWord32    :: m Word32
  -- | Generate uniformly distributed 64-bit word
  uniformWord64    :: m Word64
```

We know that all available stateful generators work in `PrimMonad`, therefore there is no need to restrict the monad,  but instead provide instances for generators themselves, similar to how `mwc-random` `sfmt` and `pcg-random`. In short, I am really against above approach.

What is actually proposed in #1 is this (naming can be debated later, eg. uniform vs gen, etc):
```haskell
class RandomPrimGen g where
    genWord8  :: PrimMonad m => g (PrimState m) -> m Word8
    genWord16 :: PrimMonad m => g (PrimState m) -> m Word16
    genWord32 :: PrimMonad m => g (PrimState m) -> m Word32
    genWord64 :: PrimMonad m => g (PrimState m) -> m Word64
    genFloat  :: PrimMonad m => g (PrimState m) -> m Float
    genDouble :: PrimMonad m => g (PrimState m) -> m Double
```

@Shimuuar successfully convinced everyone including me that generation of floating point numbers should NOT be customizable for various reasons. Therefore we are left with:

```haskell
class RandomPrimGen g where
    genWord8  :: PrimMonad m => g (PrimState m) -> m Word8
    genWord16 :: PrimMonad m => g (PrimState m) -> m Word16
    genWord32 :: PrimMonad m => g (PrimState m) -> m Word32
    genWord64 :: PrimMonad m => g (PrimState m) -> m Word64
```

Now we are finally getting to the problem this ticket raises. Some generators are not capable of generating full 32bits or full 64bits, while others are. Let's look at a pathological case, with `StdGen` which is capable of generating a range of only `[1, 2147483562]`. Note that it is 86 short to `maxBound` of  `Int32`, which means it is not even capable of generating full 31bits.

I see there being two approaches here:

1. Is the approach taken by `random` currently where the range of a one-shot generation is being specified and can be used for generating all ranges This would result in something like this:

```haskell
class RandomPrimGen g where
    -- | Maximum value that this generator is capable of producing in one go
    maxValue64 :: Proxy (g s) -> Word64
    -- | Generate `Word32` up to the `maxValue64`
    genWord32 :: PrimMonad m => g (PrimState m) -> m Word32
    -- | Generate `Word64` up to the `maxValue64`
    genWord64 :: PrimMonad m => g (PrimState m) -> m Word64
```

This would mean that the RNG implementor would have no control of how to generate values within a specific range, which has:

* advantages:
  * `random` package controls generation of ranges consistently across all possible types (same argument was provided for floating point numbers)
* disadvantages:
  * RNG implementor cannot provide the most suitable and efficient way of generating ranges for that particular generator
  * Generating of all values suffers even if the range is `(minBound, maxBound)`

2. Approach is the one @Shimuuar suggesting:

```haskell
class RandomPrimGen g where
    -- | Generate `Word32` up to and including the supplied max value
    genWord32R :: PrimMonad m => Word32 -> g (PrimState m) -> m Word32
    -- | Generate `Word32` up to and including the supplied max value
    genWord64R :: PrimMonad m => Word64 -> g (PrimState m) -> m Word64

    genWord32 :: PrimMonad m => g (PrimState m) -> m Word32
    genWord32 = genWord32R maxBound
    genWord64 :: PrimMonad m => g (PrimState m) -> m Word64
    genWord64 = genWord64R maxBound
```

I am definitely more in favor of the 2nd approach, with a few very important additions:

First of all, @Shimuuar is suggesting that there are no generators that can produce 8bits in one go more efficiently then generating `Word32` first and then reducing it to the range to `[0,255]`. This is an incorrect assumption and looking at any CRNG (like ChaCha for example) that is capable of generating one byte at a time proves this wrong. Therefore I strongly think that `Word8` and `Word16` should be included with default implementation. So we would get something along those lines:

```haskell
class RandomPrimGen g where
  -- | Generate `Word32` up to and including the supplied max value
  genWord32R :: PrimMonad m => Word32 -> g (PrimState m) -> m Word32
  -- | Generate `Word32` up to and including the supplied max value
  genWord64R :: PrimMonad m => Word64 -> g (PrimState m) -> m Word64

  genWord8 :: PrimMonad m => g (PrimState m) -> m Word8
  genWord8 = fmap fromIntegral . genWord32R (fromIntegral (maxBound :: Word8))
  genWord16 :: PrimMonad m => g (PrimState m) -> m Word16
  genWord16 = fmap fromIntegral . genWord32R (fromIntegral (maxBound :: Word16))
  genWord32 :: PrimMonad m => g (PrimState m) -> m Word32
  genWord32 = genWord32R maxBound
  genWord64 :: PrimMonad m => g (PrimState m) -> m Word64
  genWord64 = genWord64R maxBound
```

And now the final addition. Some generators are capable of generating large amounts of random data more efficiently than if you would generate it 8 bytes at a time. Therefore I suggest also adding to the above class this function:

```haskell
  -- | Use a generator to produce an array of supplied size @n@ with random values
  genPrimArray :: (PrimMonad m, Prim a) => g (PrimState m) -> Int -> m (PrimArray a)
```
Here is an example of CRNG that is capable of utilizing such interface efficiently:
https://github.com/lehins/haskell-benchmarks/pull/6

**Important note**: All of the arguments I raised here applies to the pure (splittable) generator as well

**Comment by Shimuuar** [comment]
> This is an incorrect assumption and looking at any CRNG (like ChaCha for example) that is capable of generating one byte at a time proves this wrong.

You managed to convince me that primitives for Word8/Word16 should be included as well. Only question is whether we should include `genWord8/16R` as well? Using genWord32R will require no less than 4 steps for ChaCha

**Comment by lehins** [comment]
I don't think such functions would bring any value, since using generators that produce less the 16bits of in one go (that is not full Word8/Word16) are probably terrible generators to begin with.
> Only question is whether we should include genWord8/16R as well? 


This is not really true, ChaCha is a stream cypher that generates a stream in blocks of 512bit, but it can produce up to any number of requested bytes. 
> Using genWord32R will require no less than 4 steps for ChaCha

**Comment by Shimuuar** [comment]
Now what I think about `RandomPrimGen` design. Main problem is screws pure PRNGs since their primitive is quite different: `g -> (g,Word)` instead of `PrimMonad m => g (PrimState m) -> m Word` (I use Word just as illustration). It's possible to use ST/IORef but that will require paying rather steep performance price. 

It also forces `PrimMonad` constraint which pure generators do not need. Such arrangement are bound to cause problems in the future. I can't give example out of hand but I think Monte-Carlo on tree-like structures may use pure interface.

I tried to reconcile API of both types. I'll look what I actually did tomorrow. 


### MonadRandom

One problem with interface like `RandomPrimGen` is ergonomics. Once you start writing semi-complicated Monte-Carlo passing same `gen` everywhere becomes very annoying and add a lot of visual clutter. There're two wrappers in `MonadRandom`-style for mwc-random: [mwc-probability](https://hackage.haskell.org/package/mwc%2Dprobability) and [mwc-random-monad](https://hackage.haskell.org/package/mwc%2Drandom%2Dmonad). So it's clear there's demand for such API

As usual there're cases where different tradeoff are preferable. If one mostly working with randomness it's more convenient to use monadic interface to avoid threading generator manually. If one mostly works in `PrimMonad` and occasionally needs randomness it's easier to use explicit generator. And of course there're pure generators to make situation more complicated

**Comment by lehins** [comment]
@Shimuuar I would not call it a demand, it is just one way of implementing it. Also, the APIs you pointed to are wrappers around `PrimMonad`, which proves my point that adding `RandomMonad` class is not necessary.

> So it's clear there's demand for such API

Most importantly. I was not suggesting of getting rid of `RandomGen` class. In fact I am a strong advocate of keeping splittable interface conceptually the way it is now without relying on any monads at all!!! 
> Main problem is screws pure PRNGs since their primitive is quite different: g -> (g,Word) instead of PrimMonad m => g (PrimState m) -> m Word


`random :: g -> (a, g)` is extremely simple and powerful concept that has been around for many years. If someone has a desire of wrapping  such generator in a `StateT` or in `IORef`, more power to them. In fact we could even provide one of those by default: `newtype StdPrimGen s = MutVar s StdGen` and give it instance for `RandomPrimGen`, but requiring monadic interface by default is very wrong! Here are just few reasons of top of my head:

* Wrapping it in a monad will penalize on performance!
* Deterministic parallelization of random number generation goes out the window, because now we are restricted to a monad.
* Anyone learning haskell has to learn monads before they can create random numbers, which is just cruel
* I personally don't think there is anything wrong with pure generator. The fact that it is now slow it's just due to bad implementation.
* Last, but not least. A shitload of software will have to be rewritten, just because a few guys thought it would be a nice improvement.

**I strongly recommend keeping as much backwards compatibility as possible**. Can you imagine how many programs have been written with that interface in the last 13 years that `random` was on hackage? In fact it predates hackage and I think it used to be bundled with ghc.

CC @cartazio I know you are thinking of replacing `RandomGen` with some monadic interface. Please think of arguments above before considering it.

**Comment by Shimuuar** [comment]
Another problem that I didn't bring up is how to write code that is parametric in PRNG. Say I want to write generator that produces normal or truncated normal distribution. Those are quite complicated beasts. What will I do now? I'll write it for mwc-random. With `RandomPrimGen` it becomes possible to write them for stateful PRNGs. Only question is how to reuse same code for pure PRGNs?

> Also, the APIs you pointed to are wrappers around PrimMonad, which proves my point that adding RandomMonad class is not necessary.

People went out of their way and manually wrapped tens of functions just to avoid explicit passing of generator handle.

> Wrapping it in a monad will penalize on performance!

I think it's not quite fair to propose to wrap pure generators into STRefs and complain performance impact. :) Anyway we'll need benchmarks in order to speak about 

> Deterministic parallelization of random number generation goes out the window, because now we are restricted to a monad.

It doesn't. Once you specialize from some monad to state monad everything is back.

> Anyone learning haskell has to learn monads before they can create random numbers, which is just cruel

1) One have to learn monads to do just about anything 2) old `Random` & `RandomGen` I presume will stay around 3)ability to write good libraries for working with random numbers is more important.


> I personally don't think there is anything wrong with pure generator. The fact that it is now slow it's just due to bad implementation.

Nothing! Only question is how to use them generically. Also only way to use StdGen and keep your sanity is to use state monad anyway. 


As for Random & RandomGen. I think only option is leave them alone. Maybe deprecate it. There's no way it could be improved without breaking backward compatibility. 

P.S. Exchange degenerates into I think pointless back and forth. I'll write concrete proposal over weekends so we hva something concrete to discuss instead of guessing what others are thinking

**Comment by Boarders** [comment]
@lehins : If the pure generator is just a simple newtype state monad then will that have any performance overhead? I don't think so but I am happy to be proven wrong. If you decide against a monadic interface then please at least provide combinators in the library which are the equivalent of `replicateM`, `replicateM_` and `(>>)` because it is really unpleasant having to do manual state passing just for the sake that beginners don't have to learn monads to use the library.

I'm also interested to the extent to which the library can be made modular in the kind if pure PRNG being used. I think that would be a valuable goal though it might be too infeasible in practice. To some extent that is what `RandomGen` is already meant for but I don't necessarily think it is ideal in practice.

**Comment by cartazio** [comment]
State monad and other related forms for pure rngs have zero overhead.  I
have examples of nontrivial code where ghc can evaluate away anything into
a constant values.

**Comment by lehins** [comment]
@cartazio and @Boarders I don't see you commenting on the most important point?
> Can you imagine how many programs have been written with that interface in the last 13 years that random was on hackage?

We can think of what all sort of wrappers that we can provide around `RandomGen` out of the box to make it more user friendly, be it `StateT`, `IORef`, or  even `TVar` if you wish. My point is not to break current interface, but improve on it, while fixing the performance issue. I think that should be the main goal!

@Shimuuar I don't think deprecating it is a good idea either. And I am pretty sure we can improve it drastically without breaking compatibility. PR #1 serves as real proof of that, despite that being a very short initial stab at it.
> Maybe deprecate it. There's no way it could be improved without breaking backward compatibility.

**Comment by lehins** [comment]
@Shimuuar 

1. Strongly disagree. One crucial thing you forget about that you can do without understanding monads is to learn Haskell. We don't need to kill those newcomers with state monad just to allow them to generate a random number. (I speak about it from experience, I vividly remember learning about `Random` back at university years ago, which was before I had any grasp on monads)

2. Agree
3. Mostly agree. "Ability to write good libraries for working with random numbers" is very important, but not always more important that backwards compatibility.

> 1) One have to learn monads to do just about anything 2) old Random & RandomGen I presume will stay around 3)ability to write good libraries for working with random numbers is more important.

All in all I think in the end we'll come up with something that will make everyone happy! ;) I really appreciate everyone showing interest in making `random` better!

**Comment by cartazio** [comment]
providing a non monadic interface is fine, just terrible ux :)

**Comment by Shimuuar** [comment]
> I don't think such functions would bring any value, since using generators that produce less the 16bits of in one go (that is not full Word8/Word16) are probably terrible generators to begin with.

After thinking a bit more about 8/16-bit primitives I think this argument is not correct. If we say that we need `netxWord8` because PRGNs could produce randomness in byte-sized chunks, same argument holds for `nextWord8R`. For example if we want to generate sequence of lower-case ASCII letter with native `nextWord8R` we will consume ≈1.09 bytes of generator output per char vs 4 if it's implemented as `nextWord32R`. Of course there're questions whether overhead of working at byte-sized granularity worth it. But if we want to defer this choice to PRNG implementors we should defer it completely.

**Comment by lehins** [comment]
@Shimuuar I don't really know for sure either, without some benchmarks and actual trial and error its hard to know. Your argument sort of makes sens. At the same time, I don't think we need to worry about it at the moment. I think, if a need comes up in the future for Word8R and Word16R functions we can add them in a next version.

**Comment by Shimuuar** [comment]
@lehins In fact what also bothers me is distinct lack of symmetry. In my experience most of the time it means either good reason for breaking symmetry or problems ahead

In any case I don't have strong opinion either way. Adding methods with default implementations is relatively painless

**Comment by lehins** [comment]
@Shimuuar I think I feel the same now as well.
> In any case I don't have strong opinion either way. 

We'll just add them for completeness :)

**Comment by Shimuuar** [comment]
So to summarize. Current proposal looks like:
```haskell
class RandomPrimGen g where
  genWord64  :: PrimMonad m => g (PrimState m) -> m Word64
  genWord64R :: PrimMonad m => Word64 -> g (PrimState m) -> m Word64
  genWord32  :: PrimMonad m => g (PrimState m) -> m Word32
  genWord32R :: PrimMonad m => Word32 -> g (PrimState m) -> m Word32
  -- with default implementation in terms of Word32
  genWord16  :: PrimMonad m => g (PrimState m) -> m Word16
  genWord16R :: PrimMonad m => Word16 -> g (PrimState m) -> m Word16
  genWord8   :: PrimMonad m => g (PrimState m) -> m Word8
  genWord8R  :: PrimMonad m => Word8 -> g (PrimState m) -> m Word8
```

So only remaining question is to whether provide default implementations for 32/64 bits methods and what should be implemented in terms of what. Or else to just provide enough rope for implementors. I mean functions like `defaultGenWord64R`

**Comment by lehins** [comment]
I think providing both would be the right way to go:
> provide default implementations for 32/64 bits methods ... Or else to just provide enough rope for implementors.

**Comment by idontgetoutmuch** [comment]
@lehins I am having trouble relating the proposal https://github.com/idontgetoutmuch/random/issues/5#issuecomment-589995607 to what is in your PR (https://github.com/idontgetoutmuch/random/pull/1). I've summarised the type classes in the PR below. Is `RandomGen` meant to be `RandomPrimGen`? The latter has a monadic interface and also does not include e.g. `next` and `split`.

```haskell
class Random a where
  randomRM :: MonadRandom g m => (a, a) -> g -> m a
  randomM :: MonadRandom g m => g -> m a
  randomR :: RandomGen g => (a, a) -> g -> (a, g)
  random :: RandomGen g => g -> (a, g)
  randomRs :: RandomGen g => (a, a) -> g -> [a]
  randoms :: RandomGen g => g -> [a]
  randomRIO :: (a, a) -> IO a
  randomIO :: IO a
  {-# MINIMAL randomRM, randomM #-}

class Monad m => MonadRandom g (m :: * -> *) where
  type family Seed g :: *
  restore :: Seed g -> m g
  save :: g -> m (Seed g)
  uniformWord32R :: Word32 -> g -> m Word32
  uniformWord64R :: Word64 -> g -> m Word64
  uniformWord8 :: g -> m Word8
  uniformWord16 :: g -> m Word16
  uniformWord32 :: g -> m Word32
  uniformWord64 :: g -> m Word64
  {-# MINIMAL restore, save, uniformWord32R, uniformWord64R #-}

class RandomGen g where
  type family GenSeed g :: *
    Default: Word64
  mkGen :: GenSeed g -> g
  saveGen :: g -> GenSeed g
  next :: g -> (Int, g)
  genWord8 :: g -> (Word8, g)
  genWord16 :: g -> (Word16, g)
  genWord32 :: g -> (Word32, g)
  genWord64 :: g -> (Word64, g)
  genWord32R :: Word32 -> g -> (Word32, g)
  genWord64R :: Word64 -> g -> (Word64, g)
  genRange :: g -> (Int, Int)
  split :: g -> (g, g)
  {-# MINIMAL mkGen, saveGen, next, split #-}
```

**Comment by Shimuuar** [comment]
Regarding default implementations. It's not that simple it it's not clear what should be implemented in terms of what. Even if only consider generators which produce full range of 32/64 bit words situation is not clear. There's not a single common implementation between them!

### Generates 32-bit word
```
  uniformWord32  = prng_primtive
  uniformWord64  = run uniformWord32 twice
  uniformWord32R = rejection sampling using uniformWord32
  uniformWord64R n
    | n < maxBound32 = uniformWord32R
    | otherwise      = rejection sampling using uniformWord64
```

### Generates 64-bit word

```
  uniformWord32  = fromIntegral  <$> uniformWord64
  uniformWord64  = prng_primtive
  uniformWord32R = fmap fromIntegral . uniformWord64R . fromIntegral
  uniformWord64R = rejection sampling using uniformWord64
```

I'm leaning to not adding default implementations in class definitions. Instead only providing documentation and defaults as standalone functions which PRNG implementors could reuse easily. After all adding new PRNG is not done frequently so it's OK to require to pick efficient variants manually

**Comment by lehins** [comment]
@idontgetoutmuch I think I understand where the confusion might be coming from. I did a bit of renaming of the functions. Which can be changed to something better if someone feels strongly.

* I renamed all `nextWord*` functions to `genWord*`, just because `next` implies that it will be a next eg. `Word16` in the sequence of 16bit values, while in reality it will likely (incase of splitmix for example) be next `Word64` in a sequence of 64bit values reduced to `Word16`. Therefore `gen` makes more sense. See what I mean?
* Now, I was using before `genWord*` names in the `RandomPrimGen` class that I was proposing, but that was removed in favor of more general `MonadRandom` as described in https://github.com/idontgetoutmuch/random/issues/3#issuecomment-589989429 Stateful generators use `uniform` name, so I went for that naming as well for monadic interface.

So, No. `RandomGen` is still `RandomGen`, but `MonadRandom` is what was `RandomPrimGen`, just because it can work with any monad, not just `PrimMonad`.
> Is RandomGen meant to be RandomPrimGen?

**Comment by lehins** [comment]
@Shimuuar I think this situation is pretty clear, here is a perfectly fine solution:
```haskell
class Monad m => MonadRandom g m where
  type Seed g :: *
  {-# MINIMAL save,restore,(uniformWord32R|uniformWord32),(uniformWord64R|uniformWord64) #-}
  restore :: Seed g -> m g
  save :: g -> m (Seed g)
  uniformWord32R :: Word32 -> g -> m Word32
  uniformWord32R = bitmaskWithRejection32M
  uniformWord64R :: Word64 -> g -> m Word64
  uniformWord64R = bitmaskWithRejection64M
  ... similar thing can be done for `uniformWord8R` and `uniformWord16R`, but omitted here
  uniformWord8 :: g -> m Word8
  uniformWord8 = fmap fromIntegral . uniformWord32R (fromIntegral (maxBound :: Word8))
  uniformWord16 :: g -> m Word16
  uniformWord16 = fmap fromIntegral . uniformWord32R (fromIntegral (maxBound :: Word16))
  uniformWord32 :: g -> m Word32
  uniformWord32 = uniformWord32R maxBound
  uniformWord64 :: g -> m Word64
  uniformWord64 = uniformWord64R maxBound
```

Is optimal? Definitely not for all generators. But big question is this implementation correct? I think so! This is a common pattern in Haskell and the reason for default customizable implementation.

**Comment by curiousleo** [comment]
A set of primitive generators has now been implemented. Closing.
